#!/usr/bin/env python3
"""
Emit results/module4/r_external/clusterprofiler_supplementary_pathways.R for hypergeometric
over-representation (enricher) on DEA FDR hits vs WikiPathways + PathwayCommons GMTs.

Universe = all HGNC symbols present in the Welch prerank .rnk (same gene universe as fgsea).
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import yaml

_REPO = Path(__file__).resolve().parents[1]


def _data_root() -> Path:
    env = os.environ.get("GLIOMA_TARGET_DATA_ROOT", "").strip()
    if env:
        return Path(env)
    cfg = yaml.safe_load((_REPO / "config/data_sources.yaml").read_text(encoding="utf-8"))
    return Path(cfg["data_root"].replace("/", os.sep))


def _expand(dr: Path, tmpl: str) -> Path:
    return Path(tmpl.replace("{data_root}", str(dr)).replace("/", os.sep))


def main() -> int:
    dr = _data_root()
    doc = yaml.safe_load((_REPO / "config/data_sources.yaml").read_text(encoding="utf-8"))
    ref = doc.get("references") or {}

    def p(key: str) -> Path | None:
        t = ref.get(key)
        return _expand(dr, t) if isinstance(t, str) else None

    wiki = p("wikipathways_homo_sapiens_gmt")
    pc_plain = p("pathwaycommons_all_hgnc_gmt_plain")
    hgnc = p("hgnc_complete_tsv")
    dea = _REPO / "results/module3/dea_gbm_vs_gtex_brain.tsv"
    prerank = _REPO / "results/module4/gsea/dea_welch_signed_neg_log10_p.rnk"

    plan: dict[str, Any] = {
        "data_root": str(dr.resolve()),
        "note": "Rscript results/module4/r_external/clusterprofiler_supplementary_pathways.R (after install_r_supplementary_enrichment.R)",
        "paths": {
            "dea_tsv": str(dea) if dea.is_file() else None,
            "hgnc_complete_tsv": str(hgnc) if hgnc and hgnc.is_file() else None,
            "prerank_welch": str(prerank) if prerank.is_file() else None,
            "wiki_gmt": str(wiki) if wiki and wiki.is_file() else None,
            "pathwaycommons_plain_gmt": str(pc_plain) if pc_plain and pc_plain.is_file() else None,
        },
    }

    def rstr(path: Path | None) -> str:
        if path is None:
            return "NULL"
        s = str(path.resolve()).replace("\\", "/")
        return json.dumps(s)

    out_js = _REPO / "results/module4/m4_clusterprofiler_supplementary_plan.json"
    out_r = _REPO / "results/module4/r_external/clusterprofiler_supplementary_pathways.R"
    out_js.parent.mkdir(parents=True, exist_ok=True)
    out_r.parent.mkdir(parents=True, exist_ok=True)
    out_js.write_text(json.dumps(plan, indent=2), encoding="utf-8")

    r_src = f"""# Auto-generated by scripts/build_m4_clusterprofiler_enrichment_plan.py
# WikiPathways GMT: Entrez gene IDs. PathwayCommons HGNC GMT: symbols. enricher() runs separately per ID space.
suppressPackageStartupMessages({{
  if (!requireNamespace("clusterProfiler", quietly = TRUE)) stop("Install Bioconductor clusterProfiler")
  if (!requireNamespace("data.table", quietly = TRUE)) stop("Install CRAN data.table")
  if (!requireNamespace("AnnotationDbi", quietly = TRUE)) stop("Install AnnotationDbi (Bioconductor)")
  if (!requireNamespace("org.Hs.eg.db", quietly = TRUE)) stop("Install org.Hs.eg.db for WikiPathways Entrez GMTs")
}})
library(data.table)
library(clusterProfiler)

dea_path <- {rstr(dea if dea.is_file() else None)}
hgnc_path <- {rstr(hgnc if hgnc is not None and hgnc.is_file() else None)}
rnk_path <- {rstr(prerank if prerank.is_file() else None)}
wiki_gmt <- {rstr(wiki if wiki is not None and wiki.is_file() else None)}
pc_plain <- {rstr(pc_plain if pc_plain is not None and pc_plain.is_file() else None)}
padj_cutoff <- 0.05
min_gs <- 10L
max_gs <- 500L

stopifnot(file.exists(dea_path), file.exists(hgnc_path), file.exists(rnk_path))
stopifnot(file.exists(wiki_gmt) || file.exists(pc_plain))

ens_base <- function(x) sub("\\\\.[0-9].*$", "", x)

dea <- data.table::fread(dea_path)
stopifnot(all(c("gene_id", "padj_bh") %in% names(dea)))
hg <- data.table::fread(hgnc_path)
stopifnot(all(c("ensembl_gene_id", "symbol") %in% names(hg)))
hg <- unique(hg[, .(ensembl_gene_id, symbol)], by = "ensembl_gene_id")
hg[, eb := ens_base(as.character(ensembl_gene_id))]
dea[, eb := ens_base(as.character(gene_id))]
dea <- merge(dea, hg[, .(eb, symbol)], by = "eb", all.x = TRUE)
sig <- unique(na.omit(dea[padj_bh < padj_cutoff, symbol]))
if (length(sig) < 1L) stop("No significant genes at padj_bh < ", padj_cutoff)

rnk <- data.table::fread(rnk_path, header = FALSE, col.names = c("gene", "stat"))
universe <- unique(as.character(rnk$gene))
universe <- universe[nchar(universe) > 0]
sig <- sig[sig %in% universe]
if (length(sig) < 1L) stop("No significant genes overlap prerank universe")

sym_to_entrez <- function(syms) {{
  m <- suppressMessages(AnnotationDbi::select(
    org.Hs.eg.db::org.Hs.eg.db,
    keys = unique(syms),
    keytype = "SYMBOL",
    columns = "ENTREZID"
  ))
  unique(stats::na.omit(as.character(m$ENTREZID)))
}}

enrich_one <- function(gene_ids, univ_ids, t2g_df, label) {{
  if (nrow(t2g_df) < 1L) {{
    warning("clusterProfiler enricher skipped for ", label, ": empty TERM2GENE")
    return(NULL)
  }}
  if (length(gene_ids) < 1L) {{
    warning("clusterProfiler enricher skipped for ", label, ": empty gene query set")
    return(NULL)
  }}
  if (length(univ_ids) < 1L) {{
    warning("clusterProfiler enricher skipped for ", label, ": empty universe")
    return(NULL)
  }}
  tryCatch(
    enricher(
      gene = gene_ids,
      universe = univ_ids,
      TERM2GENE = t2g_df,
      pAdjustMethod = "BH",
      pvalueCutoff = 0.05,
      qvalueCutoff = 0.2,
      minGSSize = min_gs,
      maxGSSize = max_gs
    ),
    error = function(err) {{
      warning("clusterProfiler enricher error (", label, "): ", conditionMessage(err))
      NULL
    }}
  )
}}

append_enricher_part <- function(res_parts, e, label) {{
  if (is.null(e)) return(res_parts)
  er <- tryCatch(as.data.frame(e@result), error = function(err) {{
    warning("Could not read enrichResult@result for ", label, ": ", conditionMessage(err))
    NULL
  }})
  if (is.null(er) || nrow(er) < 1L) {{
    warning("clusterProfiler returned 0 enriched terms for ", label)
    return(res_parts)
  }}
  res_parts[[length(res_parts) + 1L]] <- data.table::as.data.table(er)[, pathway_db := label]
  res_parts
}}

res_parts <- list()
cp_skip <- character()

if (file.exists(wiki_gmt)) {{
  g <- tryCatch(clusterProfiler::read.gmt(wiki_gmt), error = function(err) {{
    warning("read.gmt failed (WikiPathways): ", conditionMessage(err))
    NULL
  }})
  if (is.null(g) || nrow(g) < 1L) {{
    cp_skip <- c(cp_skip, "wiki_read_gmt_failed_or_empty")
  }} else {{
    g$term <- paste0("WP:", g$term)
    g$gene <- as.character(g$gene)
    wp_t2g <- g[, c("term", "gene")]
    sig_e <- sym_to_entrez(sig)
    univ_e <- sym_to_entrez(universe)
    sig_e <- sig_e[sig_e %in% univ_e]
    if (length(sig_e) < 1L) {{
      warning("WikiPathways enricher: no significant Entrez IDs in universe after mapping")
      cp_skip <- c(cp_skip, "wiki_no_sig_entrez_in_universe")
    }} else {{
      e <- enrich_one(sig_e, univ_e, wp_t2g, "WikiPathways_Entrez")
      res_parts <- append_enricher_part(res_parts, e, "WikiPathways_Entrez")
    }}
  }}
}} else {{
  cp_skip <- c(cp_skip, "wiki_gmt_missing")
}}

if (file.exists(pc_plain)) {{
  g <- tryCatch(clusterProfiler::read.gmt(pc_plain), error = function(err) {{
    warning("read.gmt failed (PathwayCommons): ", conditionMessage(err))
    NULL
  }})
  if (is.null(g) || nrow(g) < 1L) {{
    cp_skip <- c(cp_skip, "pc_read_gmt_failed_or_empty")
  }} else {{
    g$term <- paste0("PC:", g$term)
    g$gene <- as.character(g$gene)
    pc_t2g <- g[, c("term", "gene")]
    e <- enrich_one(sig, universe, pc_t2g, "PathwayCommons_HGNC")
    res_parts <- append_enricher_part(res_parts, e, "PathwayCommons_HGNC")
  }}
}} else {{
  cp_skip <- c(cp_skip, "pc_gmt_missing")
}}

out_tsv <- file.path(dirname(rnk_path), "clusterprofiler_supplementary_enricher.tsv")
if (length(res_parts) == 0L) {{
  detail <- if (length(cp_skip) > 0L) paste(unique(cp_skip), collapse = "; ") else "no_terms_passed_filters"
  data.table::fwrite(
    data.table::data.table(note = "no_enriched_terms", detail = detail),
    out_tsv,
    sep = "\\t"
  )
  message("Wrote ", out_tsv, " (sentinel: no enriched terms; see detail column)")
}} else {{
  res_parts <- res_parts[vapply(res_parts, function(x) data.table::is.data.table(x) && nrow(x) > 0L, logical(1L))]
  if (length(res_parts) == 0L) {{
    data.table::fwrite(
      data.table::data.table(note = "no_enriched_terms", detail = "all_parts_empty_after_filter"),
      out_tsv,
      sep = "\\t"
    )
    message("Wrote ", out_tsv, " (sentinel: empty parts filtered)")
  }} else {{
    data.table::fwrite(data.table::rbindlist(res_parts, fill = TRUE), out_tsv, sep = "\\t")
    message("Wrote ", out_tsv)
  }}
}}
"""
    out_r.write_text(r_src, encoding="utf-8")
    print(f"Wrote {out_js}")
    print(f"Wrote {out_r}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
