#!/usr/bin/env python3
"""
Build JSON + R helper for optional fgsea / clusterProfiler-style enrichment using
WikiPathways + PathwayCommons GMTs under data_root (see config/data_sources.yaml).

Does not run R; writes a runnable script under results/module4/r_external/.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

import yaml

_REPO = Path(__file__).resolve().parents[1]


def _data_root() -> Path:
    env = os.environ.get("GLIOMA_TARGET_DATA_ROOT", "").strip()
    if env:
        return Path(env)
    cfg = yaml.safe_load((_REPO / "config/data_sources.yaml").read_text(encoding="utf-8"))
    return Path(cfg["data_root"].replace("/", os.sep))


def _expand(dr: Path, tmpl: str) -> Path:
    return Path(tmpl.replace("{data_root}", str(dr)).replace("/", os.sep))


def main() -> int:
    dr = _data_root()
    doc = yaml.safe_load((_REPO / "config/data_sources.yaml").read_text(encoding="utf-8"))
    ref = doc.get("references") or {}

    def p(key: str) -> Path | None:
        t = ref.get(key)
        return _expand(dr, t) if isinstance(t, str) else None

    wiki = p("wikipathways_homo_sapiens_gmt")
    pc_gz = p("pathwaycommons_all_hgnc_gmt")
    pc_plain = p("pathwaycommons_all_hgnc_gmt_plain")
    prerank = _REPO / "results/module4/gsea/dea_welch_signed_neg_log10_p.rnk"

    paths_payload: dict[str, Any] = {
        "wikipathways_homo_sapiens_gmt": str(wiki) if wiki else None,
        "pathwaycommons_gmt_gz": str(pc_gz) if pc_gz else None,
        "pathwaycommons_gmt_plain": str(pc_plain) if pc_plain else None,
        "default_prerank_welch": str(prerank) if prerank.is_file() else None,
        "exists": {
            "wiki_gmt": wiki.is_file() if wiki else False,
            "pc_gz": pc_gz.is_file() if pc_gz else False,
            "pc_plain": pc_plain.is_file() if pc_plain else False,
            "prerank": prerank.is_file(),
        },
    }

    out_json = _REPO / "results/module4/m4_supplementary_open_enrichment_plan.json"
    out_r = _REPO / "results/module4/r_external/fgsea_supplementary_pathways.R"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_r.parent.mkdir(parents=True, exist_ok=True)

    plan = {
        "data_root": str(dr.resolve()),
        "note": "Prerank .rnk uses HGNC symbols. WikiPathways GMT uses Entrez IDs (mapped via org.Hs.eg.db); PathwayCommons HGNC GMT uses symbols. Run scripts/install_r_supplementary_enrichment.R then Rscript results/module4/r_external/fgsea_supplementary_pathways.R",
        "paths": paths_payload,
    }
    out_json.write_text(json.dumps(plan, indent=2), encoding="utf-8")

    # R paths as R strings (escape backslashes for Windows)
    def rstr(path: Path | None) -> str:
        if path is None:
            return "NULL"
        s = str(path.resolve()).replace("\\", "/")
        return json.dumps(s)

    r_src = f"""# Auto-generated by scripts/build_m4_supplementary_enrichment_plan.py — edit copies, not reruns.
# Prerank matches export_dea_gsea_prerank_rnk.py: no header; columns = HGNC symbol, signed -log10(p).
# WikiPathways GMT genes are Entrez IDs; PathwayCommons .hgnc.gmt uses HGNC symbols — separate fgsea runs + mapping.
suppressPackageStartupMessages({{
  if (!requireNamespace("fgsea", quietly = TRUE)) stop("Install Bioconductor package fgsea")
  if (!requireNamespace("data.table", quietly = TRUE)) stop("Install data.table")
  if (!requireNamespace("AnnotationDbi", quietly = TRUE)) stop("Install AnnotationDbi (Bioconductor)")
  if (!requireNamespace("org.Hs.eg.db", quietly = TRUE)) stop("Install org.Hs.eg.db for WikiPathways Entrez GMTs")
}})
library(fgsea)
library(data.table)

rnk_path <- {rstr(prerank if prerank.is_file() else None)}
wiki_gmt <- {rstr(wiki if wiki is not None and wiki.is_file() else None)}
pc_plain <- {rstr(pc_plain if pc_plain is not None and pc_plain.is_file() else None)}

if (is.null(rnk_path) || !file.exists(rnk_path)) stop("Missing prerank TSV; run DEA + m4_gsea_prerank_export or set rnk_path")
if (is.null(wiki_gmt) || !file.exists(wiki_gmt)) {{
  if (is.null(pc_plain) || !file.exists(pc_plain)) {{
    stop("No GMT files found for fgsea (WikiPathways and/or PathwayCommons under data_root)")
  }}
}}
stats <- data.table::fread(rnk_path, header = FALSE, col.names = c("gene", "stat"))
stats <- stats[is.finite(stat) & nchar(gene) > 0]
data.table::setorder(stats, -stat, gene)
ranks <- stats$stat
names(ranks) <- as.character(stats$gene)
if (length(ranks) < 15L) stop("Prerank has fewer than 15 genes after filtering; cannot run fgsea")

fgsea_one <- function(pathways, stats_vec, label) {{
  if (length(pathways) < 1L) {{
    warning("fgsea skipped for ", label, ": no gene sets after GMT load")
    return(NULL)
  }}
  if (length(stats_vec) < 15L) {{
    warning("fgsea skipped for ", label, ": ranked gene list length ", length(stats_vec), " < 15")
    return(NULL)
  }}
  tryCatch(
    fgsea::fgsea(
      pathways = pathways,
      stats = stats_vec,
      minSize = 15L,
      maxSize = 500L,
      nPermSimple = 100000L
    ),
    error = function(e) {{
      warning("fgsea error (", label, "): ", conditionMessage(e))
      NULL
    }}
  )
}}

append_fgsea_part <- function(res_parts, raw, label) {{
  if (is.null(raw)) return(res_parts)
  raw_dt <- tryCatch(
    data.table::as.data.table(raw),
    error = function(e) {{
      warning("as.data.table(fgsea) failed for ", label, ": ", conditionMessage(e))
      NULL
    }}
  )
  if (is.null(raw_dt) || nrow(raw_dt) < 1L) {{
    warning("fgsea returned 0 rows for ", label, " (no pathways passed minSize/maxSize or no rank overlap)")
    return(res_parts)
  }}
  res_parts[[length(res_parts) + 1L]] <- raw_dt[, pathway_db := label]
  res_parts
}}

res_parts <- list()
if (!is.null(wiki_gmt) && file.exists(wiki_gmt)) {{
  wp <- fgsea::gmtPathways(wiki_gmt)
  names(wp) <- paste0("WP:", names(wp))
  if (length(wp) < 1L) {{
    warning("WikiPathways: gmtPathways returned zero pathways from file")
  }} else {{
    sym <- names(ranks)
    dt <- data.table::data.table(symbol = sym, stat = as.numeric(ranks[sym]))
    map <- suppressMessages(AnnotationDbi::select(
      org.Hs.eg.db::org.Hs.eg.db,
      keys = unique(sym),
      keytype = "SYMBOL",
      columns = "ENTREZID"
    ))
    map <- map[!is.na(map$ENTREZID), ]
    map <- unique(map[, c("SYMBOL", "ENTREZID")])
    dt <- merge(dt, map, by.x = "symbol", by.y = "SYMBOL", all.y = FALSE)
    if (nrow(dt) < 1L) {{
      warning("WikiPathways fgsea skipped: no SYMBOL->ENTREZID overlap for preranked genes")
    }} else {{
      dt <- dt[, .SD[which.max(abs(stat))], by = ENTREZID]
      data.table::setorder(dt, -stat, ENTREZID)
      r_e <- dt$stat
      names(r_e) <- as.character(dt$ENTREZID)
      raw <- fgsea_one(wp, r_e, "WikiPathways_Entrez")
      res_parts <- append_fgsea_part(res_parts, raw, "WikiPathways_Entrez")
    }}
  }}
}}
if (!is.null(pc_plain) && file.exists(pc_plain)) {{
  pc <- fgsea::gmtPathways(pc_plain)
  names(pc) <- paste0("PC:", names(pc))
  raw <- fgsea_one(pc, ranks, "PathwayCommons_HGNC")
  res_parts <- append_fgsea_part(res_parts, raw, "PathwayCommons_HGNC")
}}

out_tsv <- file.path(dirname(rnk_path), "fgsea_supplementary_pathways_results.tsv")
if (length(res_parts) == 0L) {{
  data.table::fwrite(
    data.table::data.table(
      note = "no_fgsea_results",
      detail = paste0(
        "No non-empty fgsea tables; check GMT paths, prerank size (>=15 genes), ",
        "Wiki SYMBOL->ENTREZ mapping, and pathway minSize/maxSize overlap."
      )
    ),
    out_tsv,
    sep = "\\t"
  )
  message("Wrote ", out_tsv, " (sentinel: no fgsea results)")
}} else {{
  res_parts <- res_parts[vapply(res_parts, function(x) data.table::is.data.table(x) && nrow(x) > 0L, logical(1L))]
  if (length(res_parts) == 0L) {{
    data.table::fwrite(
      data.table::data.table(note = "no_fgsea_results", detail = "All fgsea parts were empty after filtering"),
      out_tsv,
      sep = "\\t"
    )
    message("Wrote ", out_tsv, " (sentinel: empty parts filtered)")
  }} else {{
    res <- data.table::rbindlist(res_parts, fill = TRUE)
    if ("pval" %in% names(res)) res <- res[order(pval)]
    data.table::fwrite(res, out_tsv, sep = "\\t")
    message("Wrote ", out_tsv)
  }}
}}
"""
    out_r.write_text(r_src, encoding="utf-8")
    print(f"Wrote {out_json}")
    print(f"Wrote {out_r}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
