#!/usr/bin/env python3
"""
Discover Rscript on this machine and persist it for Snakemake m2_edger_* rules.

Writes config/rscript_local.yaml (gitignored). Snakefile _rscript_exe() reads it after
RSCRIPT / R_HOME and before config/config.yaml.

Optional: --write-config-yaml patches config/config.yaml rscript: (for single-user repos).

Usage:
  python scripts/configure_r_for_snakemake.py
  python scripts/configure_r_for_snakemake.py --dry-run
"""

from __future__ import annotations

import argparse
import glob
import os
import re
import shutil
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def try_winreg_rscript() -> Path | None:
    if sys.platform != "win32":
        return None
    import winreg

    for key_path in (r"SOFTWARE\R-core\R", r"SOFTWARE\WOW6432Node\R-core\R"):
        try:
            with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, key_path) as k:
                install, _ = winreg.QueryValueEx(k, "InstallPath")
        except OSError:
            continue
        cand = Path(install) / "bin" / "Rscript.exe"
        if cand.is_file():
            return cand.resolve()
    return None


def discover_rscript() -> Path | None:
    """Prefer explicit env, then registry (Windows), then PATH, then Program Files glob."""
    for key in ("RSCRIPT", "GLIOMA_TARGET_RSCRIPT"):
        exe = os.environ.get(key, "").strip().strip('"')
        if exe:
            p = Path(exe).expanduser()
            if p.is_file():
                return p.resolve()

    r_home = os.environ.get("R_HOME", "").strip().strip('"')
    if r_home:
        rh = Path(r_home).expanduser()
        for name in ("Rscript.exe", "Rscript"):
            cand = rh / "bin" / name
            if cand.is_file():
                return cand.resolve()

    reg = try_winreg_rscript()
    if reg is not None:
        return reg

    for name in ("Rscript", "Rscript.exe"):
        w = shutil.which(name)
        if w:
            p = Path(w).resolve()
            if p.is_file():
                return p

    if sys.platform == "win32":
        for pattern in (
            r"C:\Program Files\R\R-*\bin\Rscript.exe",
            r"C:\Program Files (x86)\R\R-*\bin\Rscript.exe",
        ):
            found = sorted(glob.glob(pattern), reverse=True)
            if found:
                p = Path(found[0]).resolve()
                if p.is_file():
                    return p

    return None


def patch_config_yaml_rscript(cfg_path: Path, rscript_posix: str) -> None:
    raw = cfg_path.read_text(encoding="utf-8")
    line = f'rscript: "{rscript_posix}"'
    if re.search(r"(?m)^rscript:\s*", raw):
        raw_new = re.sub(r"(?m)^rscript:\s*.*$", line, raw, count=1)
    else:
        raw_new = raw.rstrip() + "\n\n" + line + "\n"
    cfg_path.write_text(raw_new, encoding="utf-8")


def persist_discovered_rscript(
    *,
    dry_run: bool = False,
    write_config_yaml: bool = False,
    rr: Path | None = None,
    banner_note: str | None = None,
) -> tuple[Path | None, int]:
    """
    Discover Rscript and write config/rscript_local.yaml. Returns (path_or_none, exit_code).
    """
    found = discover_rscript()
    if found is None:
        print(
            "Could not find Rscript. Install R for Windows from https://cran.r-project.org/ "
            "or set R_HOME / RSCRIPT, then re-run this script.",
            file=sys.stderr,
        )
        return None, 1

    posix = found.as_posix()
    print(f"Found Rscript: {found}")

    rr = rr or repo_root()
    local_path = rr / "config" / "rscript_local.yaml"
    if dry_run:
        print(f"[dry-run] would write {local_path}")
        if write_config_yaml:
            print(f"[dry-run] would patch {rr / 'config' / 'config.yaml'}")
        return found, 0

    extra = ""
    if banner_note:
        extra = f"# {banner_note}\n"
    banner = (
        "# Generated by scripts/configure_r_for_snakemake.py — do not commit (see .gitignore).\n"
        "# Snakemake reads this before config/config.yaml for m2_edger_* rules.\n"
        f"{extra}"
    )
    local_path.write_text(
        f'{banner}rscript: "{posix}"\n',
        encoding="utf-8",
    )
    print(f"Wrote {local_path}")

    if write_config_yaml:
        cfg_path = rr / "config" / "config.yaml"
        patch_config_yaml_rscript(cfg_path, posix)
        print(f"Patched rscript: in {cfg_path}")

    return found, 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Print discovered path only; do not write files.",
    )
    ap.add_argument(
        "--write-config-yaml",
        action="store_true",
        help="Also set rscript: in config/config.yaml (in addition to rscript_local.yaml).",
    )
    args = ap.parse_args()

    _, code = persist_discovered_rscript(
        dry_run=args.dry_run,
        write_config_yaml=args.write_config_yaml,
    )
    return code


if __name__ == "__main__":
    raise SystemExit(main())
